// <auto-generated />
using System;
using CCSS_Repository.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCSS_Repository.Migrations
{
    [DbContext(typeof(CCSSDBContext))]
    partial class CCSSDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CCSS_Repository.Entities.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            AccountId = "account1",
                            Address = "123 Admin Street",
                            Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 39, 936, DateTimeKind.Utc).AddTicks(8141),
                            Email = "admin@example.com",
                            Gender = true,
                            IsActive = true,
                            Name = "Admin User",
                            Password = "$2a$11$pwYMx3B/cQ1gqUfdXWWDwePJR3Z61S4evCMSegbd.x4ZXP0tquzji",
                            Phone = 1234567890,
                            RoleId = "1"
                        },
                        new
                        {
                            AccountId = "account2",
                            Address = "456 User Lane",
                            Birthday = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 62, DateTimeKind.Utc).AddTicks(7068),
                            Email = "user@example.com",
                            Gender = false,
                            IsActive = true,
                            Name = "Regular User",
                            Password = "$2a$11$mVJVBp4KkdxnK9DstzSuxuixNj0.b54OO4O4grG.3SnNJ/CX587Fm",
                            Phone = 987654321,
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("CCSS_Repository.Entities.AccountTask", b =>
                {
                    b.Property<string>("AccountTaskId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountTaskId");

                    b.HasIndex("AccountId");

                    b.HasIndex("TaskId");

                    b.ToTable("AccountTask");

                    b.HasData(
                        new
                        {
                            AccountTaskId = "accountTask1",
                            AccountId = "account1",
                            TaskId = "task1"
                        },
                        new
                        {
                            AccountTaskId = "accountTask2",
                            AccountId = "account2",
                            TaskId = "task2"
                        });
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = "category1",
                            Description = "This is Category 1",
                            Name = "Category 1"
                        },
                        new
                        {
                            CategoryId = "category2",
                            Description = "This is Category 2",
                            Name = "Category 2"
                        });
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Character", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CharacterId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            CharacterId = "character1",
                            CategoryId = "category1",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8412),
                            Description = "Description for Character 1",
                            IsActive = "true",
                            Name = "Character 1",
                            Price = 100.5
                        },
                        new
                        {
                            CharacterId = "character2",
                            CategoryId = "category2",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8415),
                            Description = "Description for Character 2",
                            IsActive = "true",
                            Name = "Character 2",
                            Price = 200.75
                        });
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Contract", b =>
                {
                    b.Property<string>("ContractId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Deposit")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("Signature")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ContractId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("Contract");

                    b.HasData(
                        new
                        {
                            ContractId = "contract1",
                            AccountId = "account1",
                            Amount = 400.0,
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8749),
                            Deposit = 100,
                            Description = "Contract for Event 1",
                            EventId = "event1",
                            Name = "Contract 1",
                            Price = 500.0,
                            Signature = true
                        },
                        new
                        {
                            ContractId = "contract2",
                            AccountId = "account2",
                            Amount = 600.0,
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8754),
                            Deposit = 200,
                            Description = "Contract for Event 2",
                            EventId = "event2",
                            Name = "Contract 2",
                            Price = 800.0,
                            Signature = false
                        });
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Event", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.ToTable("Event");

                    b.HasData(
                        new
                        {
                            EventId = "event1",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8482),
                            Description = "This is event 1",
                            Name = "Event 1",
                            Status = 1,
                            Type = "Conference"
                        },
                        new
                        {
                            EventId = "event2",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8632),
                            Description = "This is event 2",
                            Name = "Event 2",
                            Status = 2,
                            Type = "Workshop",
                            UpdateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8632)
                        });
                });

            modelBuilder.Entity("CCSS_Repository.Entities.EventCategory", b =>
                {
                    b.Property<string>("EventCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EventCategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EventId");

                    b.ToTable("EventCategory");

                    b.HasData(
                        new
                        {
                            EventCategoryId = "eventcategory1",
                            CategoryId = "category1",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8702),
                            EventId = "event1"
                        },
                        new
                        {
                            EventCategoryId = "eventcategory2",
                            CategoryId = "category2",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8707),
                            EventId = "event2"
                        });
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Feedback", b =>
                {
                    b.Property<string>("FeedbackId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FeedbackId");

                    b.HasIndex("AccountId");

                    b.ToTable("Feedback");

                    b.HasData(
                        new
                        {
                            FeedbackId = "feedback1",
                            AccountId = "account1",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8826),
                            Description = "Great service, highly recommended!",
                            Star = 5
                        },
                        new
                        {
                            FeedbackId = "feedback2",
                            AccountId = "account2",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8828),
                            Description = "Good service, but there's room for improvement.",
                            Star = 4
                        });
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Image", b =>
                {
                    b.Property<string>("ImageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CharacterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ImageId");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasFilter("[AccountId] IS NOT NULL");

                    b.HasIndex("CharacterId");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            ImageId = "image1",
                            AccountId = "account1",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8858),
                            ImageUrl = "https://example.com/image1.jpg"
                        },
                        new
                        {
                            ImageId = "image2",
                            AccountId = "account2",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8860),
                            ImageUrl = "https://example.com/image2.jpg"
                        },
                        new
                        {
                            ImageId = "image3",
                            CharacterId = "character1",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8863),
                            ImageUrl = "https://example.com/image3.jpg"
                        },
                        new
                        {
                            ImageId = "image4",
                            CharacterId = "character2",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8865),
                            ImageUrl = "https://example.com/image4.jpg"
                        });
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.ToTable("Payment");

                    b.HasData(
                        new
                        {
                            PaymentId = "payment1",
                            ContractId = "contract1",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8988),
                            Status = 1,
                            TransactionId = "TXN123456",
                            Type = "Credit Card"
                        },
                        new
                        {
                            PaymentId = "payment2",
                            ContractId = "contract2",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8991),
                            Status = 0,
                            TransactionId = "TXN789012",
                            Type = "Bank Transfer"
                        });
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleName")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = "1",
                            Description = "Administrator role",
                            RoleName = 1
                        },
                        new
                        {
                            RoleId = "2",
                            Description = "Regular user role",
                            RoleName = 2
                        });
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Task", b =>
                {
                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TaskId");

                    b.ToTable("Task");

                    b.HasData(
                        new
                        {
                            TaskId = "task1",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(6739),
                            Description = "This is task 1",
                            IsActive = true,
                            Location = "Location 1",
                            Name = "Task 1",
                            UpdateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(6746)
                        },
                        new
                        {
                            TaskId = "task2",
                            CreateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(6761),
                            Description = "This is task 2",
                            IsActive = true,
                            Location = "Location 2",
                            Name = "Task 2",
                            UpdateDate = new DateTime(2025, 2, 8, 9, 57, 40, 190, DateTimeKind.Utc).AddTicks(8016)
                        });
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Account", b =>
                {
                    b.HasOne("CCSS_Repository.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CCSS_Repository.Entities.AccountTask", b =>
                {
                    b.HasOne("CCSS_Repository.Entities.Account", "Account")
                        .WithMany("AccountTasks")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCSS_Repository.Entities.Task", "Task")
                        .WithMany("AccountTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Character", b =>
                {
                    b.HasOne("CCSS_Repository.Entities.Category", "Category")
                        .WithMany("Characters")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Contract", b =>
                {
                    b.HasOne("CCSS_Repository.Entities.Account", "Account")
                        .WithOne("Contract")
                        .HasForeignKey("CCSS_Repository.Entities.Contract", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCSS_Repository.Entities.Event", "Event")
                        .WithOne("Contract")
                        .HasForeignKey("CCSS_Repository.Entities.Contract", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CCSS_Repository.Entities.EventCategory", b =>
                {
                    b.HasOne("CCSS_Repository.Entities.Category", "Category")
                        .WithMany("EventCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCSS_Repository.Entities.Event", "Event")
                        .WithMany("EventCategories")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Feedback", b =>
                {
                    b.HasOne("CCSS_Repository.Entities.Account", "Account")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Image", b =>
                {
                    b.HasOne("CCSS_Repository.Entities.Account", "Account")
                        .WithOne("Image")
                        .HasForeignKey("CCSS_Repository.Entities.Image", "AccountId");

                    b.HasOne("CCSS_Repository.Entities.Character", "Character")
                        .WithMany("Images")
                        .HasForeignKey("CharacterId");

                    b.Navigation("Account");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Payment", b =>
                {
                    b.HasOne("CCSS_Repository.Entities.Contract", "Contract")
                        .WithOne("Payment")
                        .HasForeignKey("CCSS_Repository.Entities.Payment", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Account", b =>
                {
                    b.Navigation("AccountTasks");

                    b.Navigation("Contract")
                        .IsRequired();

                    b.Navigation("Feedbacks");

                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Category", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("EventCategories");
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Character", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Contract", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Event", b =>
                {
                    b.Navigation("Contract")
                        .IsRequired();

                    b.Navigation("EventCategories");
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CCSS_Repository.Entities.Task", b =>
                {
                    b.Navigation("AccountTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
